### ISSUE TITLE
TypeError: find_gags() takes at least 14 arguments (13 given)

### ISSUE THREAD

**Issue by ladworkin** [jdhogan/gagfinder#1]
```
./gagfinder-cli -c HS -i ~/Desktop/GAGfinder_test/STD_1_378_15V_170218_01.mzML -n 10 -m 5 -z -3 -x y

Importing modules and functions... Done!
Checking user arguments... Done!

Traceback (most recent call last):
  File "/Users/jdhogan5/Desktop/Zaia Lab/projects/gagfinder/bin/gagfinder-cli.py", line 144, in <module>
  File "/Users/jdhogan5/Desktop/Zaia Lab/projects/gagfinder/bin/gagfinder-cli.py", line 127, in main

TypeError: find_gags() takes at least 14 arguments (13 given)
```

This error pops up when running the mac cli in the supplied **gagfinder-cli_mac.zip** asset. The error message seems to indicate that I'm supplying one less argument than is necessary in order for `find_gags` to run correctly. However, I am supplying all arguments explicitly required in the README for gagfinder to run.

In addition, when I check the number of arguments for the same function in both the source code assets (**.zip** and **.tar.gz**), `find_gags` only takes **13** arguments. Could there be an error in the **gagfinder-cli_mac.zip** asset? Happy to provide more information if necessary.

**Comment by jdhogan** [comment]
Hello,

Thanks for reaching out. I'm sorry you're having difficulties using GAGfinder. Could you send me the mzML file and associated information (precursor m/z, precursor charge, reducing end tag, etc.) so I can test it? Thanks!

Cheers,
JD

**Comment by ladworkin** [comment]
Hi JD,

Of course, and thanks for your patience while I got around to replying. I've attached the mzML file below. Associated information is as follows:

  -c gag class of spectrum: **HS**     
  -i Input mzML file: **STD_1_378_15V_170218_01.mzML**
  -r Reducing end derivatization: **NA**
  -n Number of top results to return: **10**
  -p Percentage of top results to return: **NA**
  -a Which metal is adducted: **NA**
  -t Number of adducted metals: **NA**
  -g Reagent used: **NA**
  -m Precursor m/z: **378**
  -z Precursor charge: **-1**
  -s Number of sulfate losses to consider: **0**
  -x Has the noise already been removed: **Y**


Current command:
`./gagfinder-cli -c HS -i ~/Desktop/GAGfinder_test/STD_1_378_15V_170218_01.mzML -n 10 -m 378 -z -1 -x y`


[STD_1_378_15V_170218_01.mzML.zip](https://github.com/jdhogan/gagfinder/files/2565128/STD_1_378_15V_170218_01.mzML.zip)

**Comment by tarsisferreira** [comment]
Try adding the -a flag, it worked for me.

**Comment by jdhogan** [comment]
Hi,

I cannot replicate your problem with this file, mostly because I believe it was corrupted in the zipping process (see attached). Did using the -a flag work for you? Could you respond with your exact command?

Also, it appears that your precursor charge is -1, which will not work as GAGfinder is currently configured, because GAGfinder does not test fragment charge states equal to the precursor, only between 0 and the precursor + 1, so GAGfinder would not be able to test any fragments in this spectrum. If your precursor charge is -1, I could do a special analysis for you and send you the results.

Cheers,
JD

**Comment by ladworkin** [comment]
Hi @jdhogan, 

It turns out the file was corrupted while being generated by proteowizard, causing the mzML format to be truncated. Sorry for not catching that sooner. As a result, I've not been able to test with the -a flag, but I'll be sure to pass the information regarding precursor charge and your offer over to the Mass spectrometrist in lab. 

Thanks for your feedback!
